### ISSUE TITLE
How do you see the dns structure?

### ISSUE THREAD

**Issue by BryanCrotaz** [lifegadget/aws-pusher#1]
We have to be careful about wildcard SSL certs - they don't allow two levels of subdomain.

so we can have `version-1-2-3.domain.com` but not `1.2.3.version.domain.com`

How were you intending your domain diagram to be mapped into domain names?

**Comment by yankeeinlondon** [comment]
Yeah I was thinking a dasherized naming convention would be the best way to provide structured naming below the first level.

**Comment by yankeeinlondon** [comment]
Take a look at the example I put in the README for a tentative starting point to the approach.

**Comment by BryanCrotaz** [comment]
Saw the drawing but didn't spot the dasherising

Bryan Crotaz
Silver Curve

On 22 Apr 2015, at 07:17, Ken Snyder notifications@github.com wrote:

Take a look at the example I put in the README for a tentative starting
point to the approach.
